### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by nauxliu** [transferwise/pipelinewise-tap-mysql#109]
**Describe the bug**
Syncs are failing with the error, not sure what happened.

**To Reproduce**

**Your environment**
 - Version of tap: 1.5.1
 - Version of python: 3.8.13

**Additional context**
```
time=2022-04-25 12:44:09 logger_name=tap_mysql log_level=INFO message=Server Parameters: version: 8.0.23, wait_timeout: 28800, innodb_lock_wait_timeout: 3600, max_allowed_packet: 67108864, interactive_timeout: 28800
time=2022-04-25 12:44:09 logger_name=tap_mysql log_level=INFO message=Server SSL Parameters(blank means SSL is not active): [ssl_version: ], [ssl_cipher: ]
time=2022-04-25 12:44:10 logger_name=transform_field log_level=INFO message=Transformation type is SET-NULL, no need to do any validation.
time=2022-04-25 12:44:10 logger_name=tap_mysql log_level=INFO message=Using provided server_id=938705631
time=2022-04-25 12:44:10 logger_name=tap_mysql log_level=INFO message=Starting logical replication from binlog file ['mysql-bin-changelog.300547', 584534]
time=2022-04-25 12:44:10 logger_name=tap_mysql log_level=INFO message=Current Master binlog file and pos: mysql-bin-changelog.300562 2017652
time=2022-04-25 12:44:10 logger_name=singer log_level=INFO message=METRIC: {"type": "timer", "metric": "job_duration", "value": 0.31824755668640137, "tags": {"job_type": "sync_binlog", "status": "failed"}}
time=2022-04-25 12:44:10 logger_name=tap_mysql log_level=CRITICAL message=list index out of range
Traceback (most recent call last):
  File "/app/.virtualenvs/tap-mysql/bin/tap-mysql", line 8, in <module>
    sys.exit(main())
  File "/app/.virtualenvs/tap-mysql/lib/python3.8/site-packages/tap_mysql/__init__.py", line 443, in main
    raise exc
  File "/app/.virtualenvs/tap-mysql/lib/python3.8/site-packages/tap_mysql/__init__.py", line 440, in main
    main_impl()
  File "/app/.virtualenvs/tap-mysql/lib/python3.8/site-packages/tap_mysql/__init__.py", line 433, in main_impl
    do_sync(mysql_conn, args.config, catalog, state)
  File "/app/.virtualenvs/tap-mysql/lib/python3.8/site-packages/tap_mysql/__init__.py", line 385, in do_sync
    sync_binlog_streams(mysql_conn, binlog_catalog, config, state)
  File "/app/.virtualenvs/tap-mysql/lib/python3.8/site-packages/tap_mysql/__init__.py", line 368, in sync_binlog_streams
    binlog.sync_binlog_stream(mysql_conn, config, binlog_streams_map, state)
  File "/app/.virtualenvs/tap-mysql/lib/python3.8/site-packages/tap_mysql/sync_strategies/binlog.py", line 882, in sync_binlog_stream
    _run_binlog_sync(mysql_conn, reader, binlog_streams_map, state, config, end_log_file, end_log_pos)
  File "/app/.virtualenvs/tap-mysql/lib/python3.8/site-packages/tap_mysql/sync_strategies/binlog.py", line 743, in _run_binlog_sync
    processed_rows_events = handle_update_rows_event(binlog_event,
  File "/app/.virtualenvs/tap-mysql/lib/python3.8/site-packages/tap_mysql/sync_strategies/binlog.py", line 495, in handle_update_rows_event
    for row in event.rows:
  File "/app/.virtualenvs/tap-mysql/lib/python3.8/site-packages/pymysqlreplication/row_event.py", line 458, in rows
    self._fetch_rows()
  File "/app/.virtualenvs/tap-mysql/lib/python3.8/site-packages/pymysqlreplication/row_event.py", line 453, in _fetch_rows
    self.__rows.append(self._fetch_one_row())
  File "/app/.virtualenvs/tap-mysql/lib/python3.8/site-packages/pymysqlreplication/row_event.py", line 544, in _fetch_one_row
    row["after_values"] = self._read_column_data(self.columns_present_bitmap2)
  File "/app/.virtualenvs/tap-mysql/lib/python3.8/site-packages/pymysqlreplication/row_event.py", line 189, in _read_column_data
    values[name] = column.enum_values[
IndexError: list index out of range
time=2022-04-25 12:44:10 logger_name=target_snowflake log_level=INFO message=Getting catalog objects from table cache...
time=2022-04-25 12:44:10 logger_name=transform_field log_level=INFO message=Exiting normally
```

**Comment by nauxliu** [comment]
Related issue: https://github.com/julien-duponchelle/python-mysql-replication/issues/285
