### ISSUE TITLE
Compatibility with mysql 8 

### ISSUE THREAD

**Issue by tchiotludo** [transferwise/pipelinewise-tap-mysql#65]
**Describe the bug**
The tap seems to be not comptible with mysql 8.

Trying to connect to a mysql 8 with this docker-compose file:  
```yaml
version: "3.6"

services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql_passwd
      MYSQL_DATABASE: kestra
    ports:
      - "3306:3306"
````
Will lead to this error when running `./bin/tap-mysql --config config.json --discover` :  

```
time=2021-04-14 21:56:40 name=tap_mysql level=CRITICAL message=255
Traceback (most recent call last):
  File "./bin/tap-mysql", line 8, in <module>
    sys.exit(main())
  File "/tmp/working-dir6894064037233645498/lib/python3.8/site-packages/tap_mysql/__init__.py", line 406, in main
    raise exc
  File "/tmp/working-dir6894064037233645498/lib/python3.8/site-packages/tap_mysql/__init__.py", line 403, in main
    main_impl()
  File "/tmp/working-dir6894064037233645498/lib/python3.8/site-packages/tap_mysql/__init__.py", line 386, in main_impl
    log_server_params(mysql_conn)
  File "/tmp/working-dir6894064037233645498/lib/python3.8/site-packages/tap_mysql/__init__.py", line 351, in log_server_params
    with connect_with_backoff(mysql_conn) as open_conn:
  File "/tmp/working-dir6894064037233645498/lib/python3.8/site-packages/backoff/_sync.py", line 95, in retry
    ret = target(*args, **kwargs)
  File "/tmp/working-dir6894064037233645498/lib/python3.8/site-packages/tap_mysql/connection.py", line 28, in connect_with_backoff
    connection.connect()
  File "/tmp/working-dir6894064037233645498/lib/python3.8/site-packages/pymysql/connections.py", line 931, in connect
    self._get_server_information()
  File "/tmp/working-dir6894064037233645498/lib/python3.8/site-packages/pymysql/connections.py", line 1269, in _get_server_information
    self.server_charset = charset_by_id(lang).name
  File "/tmp/working-dir6894064037233645498/lib/python3.8/site-packages/pymysql/charset.py", line 39, in by_id
    return self._by_id[id]
KeyError: 255
```

Just changing to `image: mysql:5.7` and no more issue. 

Related to version : 
```
PyMySQL                    0.7.11
```
see this : 
- https://stackoverflow.com/a/47622747/1590168
- https://github.com/PyMySQL/PyMySQL/commit/4b7e9c98c0441449352d732f6a2453e4c868505c?diff=split

**Your environment**
 - Version of tap: 1.4.3
 - Version of python: 3.8.5

**Comment by aairey** [comment]
See also https://github.com/transferwise/pipelinewise/issues/418

**Comment by aairey** [comment]
@koszti  @Samira-El 
In Singer.io they have solved this already, including the datetime incompatibilities, can we implement the same changes as in these two PRs?

https://github.com/singer-io/tap-mysql/pull/116
https://github.com/singer-io/tap-mysql/pull/118

**Comment by koszti** [comment]
@aairey we bumped to pymysql-1 (#51) and mysql-replication-0.24 (#70) that adds mysql 8 support. We need to test if this is really working.

The singer fix looks like a bit of a workaround with monkey patching libraries. Seems like it's now supported properly by the bumped dependencies above. Can you please help somehow how the current master branch behaves with mysql-8?

**Comment by aairey** [comment]
How can we test this master branch of mysql-tap on the regular transferwise/pipelinewise?

**Comment by TeddyCr** [comment]
@koszti I am wondering if there are any updates on this issue. Running MySQL 8 I had the exact same error and had to implement the fix described [here](https://stackoverflow.com/questions/45368336/error-keyerror-255-when-executing-pymysql-connect)

**Comment by msardana94** [comment]
Do we know when #51 PR will be released?

**Comment by ayhanaltunkaynak** [comment]
I built as suggested. But when I run I got the following errors.

```
time=2021-12-13 14:47:35 logger_name=pipelinewise.fastsync.commons.tap_mysql log_level=INFO message=Running query: SET @@session.time_zone="+0:00"
time=2021-12-13 14:47:35 logger_name=pipelinewise.fastsync.mysql_to_snowflake log_level=ERROR message='Connection' object has no attribute 'execute'

Traceback (most recent call last):
  File "/app/pipelinewise/fastsync/mysql_to_snowflake.py", line 95, in sync_table
    mysql.open_connections()
  File "/app/pipelinewise/fastsync/commons/tap_mysql.py", line 98, in open_connections
    self.run_session_sqls()
  File "/app/pipelinewise/fastsync/commons/tap_mysql.py", line 110, in run_session_sqls
    self.query(sql)
  File "/app/pipelinewise/fastsync/commons/tap_mysql.py", line 145, in query
    cur.execute(query, params)
AttributeError: 'Connection' object has no attribute 'execute'
```

**Comment by jmriego** [comment]
it's working here! the fastsync seems like it's still broken but I'm testing by upgrading to `PyMySQL==0.9.3`. From the messages I've seen it looks like that's all that it's needed as the queries have been updated already

**Comment by Samira-El** [comment]
Does it work if you set `PyMySQL==1.0.2` in pipelinewise requirements?

**Comment by ayhanaltunkaynak** [comment]
Modified the following lines as follow in the pipelinewise/fastsync/commons/tap_mysql.py file. 
```
144:            with conn.cursor() as cur:
364:        with self.conn_unbuffered.cursor() as cur:
```

The full sync is started but while creating the table on the Snowflake side it failed. The column name is not correctly set.

Table definition at source:
```
mysql> show create table mysql8_test\G
*************************** 1. row ***************************
       Table: mysql8_test
Create Table: CREATE TABLE `mysql8_test` (
  `id` int NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1
1 row in set (0.04 sec)```

The create statement on Snowflake:

```
CREATE OR REPLACE TABLE dba_data."MYSQL8_TEST_TEMP" (None VARCHAR,_SDC_EXTRACTED_AT TIMESTAMP_NTZ,_SDC_BATCHED_AT TIMESTAMP_NTZ,_SDC_DELETED_AT VARCHAR, PRIMARY KEY ("ID"))```

**Comment by jmriego** [comment]
yes, I'm finding the same issue. That's happening because MySQL 8 now returns those columns in upper case. This is what I'm testing now:
```
@@ -155,11 +155,11 @@ class FastSyncTapMySql:
         """
         Get the actual incremental key position in the table
         """
-        result = self.query('SELECT MAX({}) AS key_value FROM {}'.format(replication_key, table))
+        result = self.query('SELECT MAX({}) AS KEY_VALUE FROM {}'.format(replication_key, table))
         if len(result) == 0:
             raise Exception('Cannot get replication key value for table: {}'.format(table))
 
-        mysql_key_value = result[0].get('key_value')
+        mysql_key_value = result[0].get('KEY_VALUE')
         key_value = mysql_key_value
 
         # Convert msyql data/datetime format to JSON friendly values
@@ -216,9 +216,9 @@ class FastSyncTapMySql:
 
         sql = f"""
                 SELECT column_name,
-                    data_type,
-                    column_type,
-                    safe_sql_value
+                    DATA_TYPE,
+                    COLUMN_TYPE,
+                    SAFE_SQL_VALUE
                 FROM (SELECT column_name,
                             data_type,
                             column_type,
@@ -273,9 +273,10 @@ class FastSyncTapMySql:
         Map MySQL column types to equivalent types in target
         """
         mysql_columns = self.get_table_columns(table_name)
+        #from remote_pdb import set_trace; set_trace()
         mapped_columns = [
-            '{} {}'.format(safe_column_name(pc.get('column_name'), self.target_quote),
-                           self.tap_type_to_target_type(pc.get('data_type'), pc.get('column_type')))
+            '{} {}'.format(safe_column_name(pc.get('COLUMN_NAME'), self.target_quote),
+                           self.tap_type_to_target_type(pc.get('DATA_TYPE'), pc.get('COLUMN_TYPE')))
             for pc in mysql_columns]
 
         return {
```

**Comment by msardana94** [comment]
We built the tap from master branch and it's working fine for us with mysql 8 and redshift target.

**Comment by ayhanaltunkaynak** [comment]
I've tested using different versions of MySQL 8, respectively 8.0.23,8.0.25,8.0.26, and 8.0.27. And it is working fine.

**Comment by Samira-El** [comment]
Thanks folks, would be cool to submit a PR to Pipelinewise repo to make FastSync work with Mysql 8.

**Comment by aairey** [comment]
Hi @Samira-El transferwise/pipelinewise#862 was submitted.
Can you review?

**Comment by aairey** [comment]
Any update here @Samira-El @koszti ?

**Comment by ShahBinoy** [comment]
is this ticket still open ?

**Comment by aairey** [comment]
This is still needed and then we can close it, I believe.

https://github.com/transferwise/pipelinewise/pull/993
